add more robusto gusto

diff --git a/egressip/templates/egress-ip-test-job.yaml b/egressip/templates/egress-ip-test-job.yaml
--- a/egressip/templates/egress-ip-test-job.yaml
+++ b/egressip/templates/egress-ip-test-job.yaml
@@ -17,7 +17,9 @@ spec:
   template:
     spec:
       containers:
-        - image: registry.redhat.io/openshift4/ose-cli:latest
+        - name: curl-test
+          imagePullPolicy: IfNotPresent
+          image: registry.redhat.io/openshift4/ose-cli:latest
           env:
             - name: TARGET_ENDPOINT
               value: "{{ $baseValues.targetCURLTestEndpoint }}"
@@ -25,19 +27,84 @@ spec:
               valueFrom:
                 fieldRef:
                   fieldPath: spec.nodeName
+            - name: MY_POD_NAMESPACE
+              valueFrom:
+                fieldRef:
+                  fieldPath: metadata.namespace
             - name: POD_NAME
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.name
+            - name: EGRESS_IP_NAME
+              value: "{{ .name }}"
           command:
             - /bin/bash
             - -c
             - |
-              curl -kv --max-time 10 "$TARGET_ENDPOINT/?pod=$POD_NAME&node=$MY_NODE_NAME" || exit 1
-          name: curl-test
+              #!/usr/bin/env bash
 
-          imagePullPolicy: IfNotPresent
-          name: curl-test
+              EGRESS_IPS=$(oc get egressip $EGRESS_IP_NAME -o jsonpath='{.spec.egressIPs}')
+              echo "Egress IPs for $EGRESS_IP_NAME: $EGRESS_IPS"
+              # Strip brackets and spaces from EGRESS_IPS
+              EGRESS_IPS_CLEAN=$(echo $EGRESS_IPS | tr -d '[] ')
+              echo "Cleaned Egress IPs: $EGRESS_IPS_CLEAN"
+              # Clean the IP list for use in the curl test
+              EGRESS_IPS=$(echo $EGRESS_IPS_CLEAN | sed 's/","/ /g' | tr -d '"')
+
+              # Loop through the EgressIPs and test each one with a separate Job
+              for IP in $EGRESS_IPS; do
+                echo "Preparing to test Egress IP: $IP"
+
+                # Create a new Job that will run the curl command from a pod with the matching egress IP
+                cat <<EOF | kubectl create -f -
+              apiVersion: batch/v1
+              kind: Job
+              metadata:
+                generateName: ${EGRESS_IP_NAME}-
+                namespace: default
+              spec:
+                template:
+                  spec:
+                    containers:
+                      - name: curl-test
+                        env:
+                          - name: EGRESS_IP
+                            value: "${IP}"
+                          - name: EGRESS_IP_NAME
+                            value: "${EGRESS_IP_NAME}"
+                          - name: TARGET_ENDPOINT
+                            value: "${TARGET_ENDPOINT}"
+                          - name: MY_NODE_NAME
+                            valueFrom:
+                              fieldRef:
+                                fieldPath: spec.nodeName
+                          - name: MY_POD_NAMESPACE
+                            valueFrom:
+                              fieldRef:
+                                fieldPath: metadata.namespace
+                          - name: POD_NAME
+                            valueFrom:
+                              fieldRef:
+                                fieldPath: metadata.name
+                        image: registry.redhat.io/openshift4/ose-cli:latest
+                        command: ["/bin/sh", "-c"]
+                        args:
+                          - |
+                            #!/usr/bin/env bash
+                            echo "Testing Egress IP: $EGRESS_IP"
+                            # Loop our curl request 5 times until we get a successful response
+                            for i in {1..5}; do
+                              curl -kv --retry --retry-all-errors --max-time 10 "$TARGET_ENDPOINT/?pod=$POD_NAME&node=$MY_NODE_NAME&ip=$EGRESS_IP"
+                              if [ $? -eq 0 ]; then
+                                echo "Curl request succeeded on attempt $i"
+                                break
+                              fi
+                              echo "Curl request failed on attempt $i"
+                            done
+                    restartPolicy: Never
+              EOF
+              done
+
       dnsPolicy: ClusterFirst
       restartPolicy: OnFailure
       terminationGracePeriodSeconds: 30
